const hampersProducts = [
    {
        id: 1,
        name: "Gourmet Delight Hamper",
        description: "A premium selection of gourmet treats, perfect for food lovers.",
        itemsIncluded: ["Artisan Cheese", "Organic Crackers", "Gourmet Chocolates", "Olives"],
        price: 79.99,
        category: "Gourmet",
        stock: 20,
        imageUrl: "https://example.com/images/gourmet-hamper.jpg",
    },
    {
        id: 2,
        name: "Wellness Hamper",
        description: "A thoughtfully curated collection of wellness products to promote relaxation and health.",
        itemsIncluded: ["Herbal Teas", "Aromatherapy Candles", "Organic Honey", "Bath Salts"],
        price: 65.50,
        category: "Wellness",
        stock: 15,
        imageUrl: "https://example.com/images/wellness-hamper.jpg",
    },
    {
        id: 3,
        name: "Luxury Spa Hamper",
        description: "Pamper yourself with luxurious spa essentials, perfect for unwinding.",
        itemsIncluded: ["Scented Candles", "Body Scrub", "Face Mask", "Body Lotion"],
        price: 99.99,
        category: "Luxury",
        stock: 10,
        imageUrl: "https://example.com/images/luxury-spa-hamper.jpg",
    },
    {
        id: 4,
        name: "Celebration Hamper",
        description: "A celebratory hamper filled with indulgent treats for special occasions.",
        itemsIncluded: ["Champagne", "Gourmet Chocolates", "Truffles", "Fruit Preserves"],
        price: 120.00,
        category: "Celebration",
        stock: 8,
        imageUrl: "https://example.com/images/celebration-hamper.jpg",
    },
    {
        id: 5,
        name: "Family Fun Hamper",
        description: "A hamper with fun treats and games for the whole family to enjoy.",
        itemsIncluded: ["Board Game", "Popcorn", "Assorted Snacks", "Chocolate Bars"],
        price: 55.00,
        category: "Family",
        stock: 25,
        imageUrl: "https://example.com/images/family-fun-hamper.jpg",
    },
    {
        id: 6,
        name: "Festive Cheer Hamper",
        description: "A festive collection of holiday treats to spread cheer.",
        itemsIncluded: ["Fruit Cake", "Mulled Wine", "Gingerbread Cookies", "Christmas Ornaments"],
        price: 89.99,
        category: "Festive",
        stock: 18,
        imageUrl: "https://example.com/images/festive-cheer-hamper.jpg",
    },
    {
        id: 7,
        name: "Healthy Start Hamper",
        description: "A collection of healthy snacks and superfoods for a fresh start.",
        itemsIncluded: ["Granola Bars", "Dried Fruits", "Nuts", "Protein Shakes"],
        price: 49.99,
        category: "Health",
        stock: 30,
        imageUrl: "https://example.com/images/healthy-start-hamper.jpg",
    },
    {
        id: 8,
        name: "Healthy Start Hamper",
        description: "A collection of healthy snacks and superfoods for a fresh start.",
        itemsIncluded: ["Granola Bars", "Dried Fruits", "Nuts", "Protein Shakes"],
        price: 49.99,
        category: "Health",
        stock: 30,
        imageUrl: "https://example.com/images/healthy-start-hamper.jpg",
    },
    {
        id: 9,
        name: "Healthy Start Hamper",
        description: "A collection of healthy snacks and superfoods for a fresh start.",
        itemsIncluded: ["Granola Bars", "Dried Fruits", "Nuts", "Protein Shakes"],
        price: 49.99,
        category: "Health",
        stock: 30,
        imageUrl: "https://example.com/images/healthy-start-hamper.jpg",
    },
];

export default hampersProducts